### ISSUE TITLE
Getting error when iam trying to import YLprogress bar in my code.

### ISSUE THREAD

**Issue by subinrevi** [yannickl/YLProgressBar#19]
Hi i ran the sample code and its working fine, but when i imported the YLProgressBar to my project iam getting an error. Do i need to install Cocoa Pods? The error in .h file shows "Funcion definition is not allowed here" . I am using Xcode 6.0.1

**Comment by yannickl** [comment]
Hi,

Sorry for the late. Yes you can change the track color by modifying the `trackTintColor` property.

**Comment by subinrevi** [comment]
Hi Thanks for the reply. Is there an option to stop the animating progress color and keep it without animation?

**Comment by subinrevi** [comment]
Hi Thanks for the reply. Is there an option to stop the animating progress color and keep it without animation? Also when i try to change the trackTintColor to light grey a black line appears on top border of the progress bar. When i tested it in your sample code also it was there. You can see it clearly when the "trackTintColor" is white.

**Comment by yannickl** [comment]
Hi,

you can stop the animation by setting the `stripesAnimated` property. To remove the grey line you have to disable the gloss effect thanks to the `hideGloss` property.

**Comment by subinrevi** [comment]
Hi,

    Thanks for your swift reply. I was able to change both those issues and its working fine. Would like to let you know theres a minor design issue in it. A thin dark line appears above the top corner of the progress bar. Its visible only when we use light colors for the track color property. I have tested it in your sample code as well. Attached a screenshot with this. Please check.

![screen shot 2015-01-13 at 12 18 56 pm](https://cloud.githubusercontent.com/assets/8567369/5716967/701a013e-9b1e-11e4-9410-7115ca6711a3.png)

Thanks 
Subin.

**Comment by yannickl** [comment]
Hi,

Have you tried with the last version (3.5.1)? I have fixed this issue in the last release.

**Comment by subinrevi** [comment]
No I havent. Will try

Thanks.

**Comment by subinrevi** [comment]
Hi,
       Checked the latest code and its fine :)

**Comment by yannickl** [comment]
Great! I close the issue. :)
