### ISSUE TITLE
Why is the text only shown at 30%?

### ISSUE THREAD

**Issue by sambudda** [yannickl/YLProgressBar#20]
I am using this control in my app

If I set it to 10% I don't see the text saying 10% on the bar. It only shows up if it goes above 30%. How can I fix that?

[_progressBarRoundedFat setProgress:0.1f animated:animated];

**Comment by sambudda** [comment]
Look at these screenshots. My bar is close to 28% and I don't see anything. I only see if it goes above 30% what is going on?
![ios simulator screen shot jan 19 2015 8 41 07 pm](https://cloud.githubusercontent.com/assets/3536867/5810905/df63d0d6-a01b-11e4-9754-6ca0859e74f8.png)
![ios simulator screen shot jan 19 2015 8 41 21 pm](https://cloud.githubusercontent.com/assets/3536867/5810910/e89a8122-a01b-11e4-929b-867dd916313c.png)

**Comment by yannickl** [comment]
Hi,

This is an expected behaviour because when the track bar is too short there is no way to display the indicator text properly. I can may be decrease the threshold, but the problem will occur for small values.

If you have any suggestion please keep me in touch.

**Comment by sambudda** [comment]
There is clearly something wrong with the logic here. As you can see there is still plenty of space left on the progress bar and yet it doesn't show 28%. Why do you need a text box that big? I can understand that the bar will be too small between 0 - 10% but after that it can accommodate text. Let me know where in the code I need to tweak and I will play around a bit to get it working and post code solution here.

**Comment by yannickl** [comment]
Yes I know, this is may be not a good solution. May be it is better to shrink the text until very low values. I'm open to new suggestion. :)

Here is the code: https://github.com/yannickl/YLProgressBar/blob/master/YLProgressBar/YLProgressBar.m#L558

**Comment by sambudda** [comment]
I just tried uncommenting this code out and it seems promising. What it does is that it keeps the text in the bigger format as long as possible for it to fit and for lower values like 0 - 11% it shrinks the text down. It looks a little goofy between 0 - 11 but then the text adjusts its self on the screen. I recommend this should be made as a option for others to turn on/off

/* 
    if (CGRectGetWidth(innerRect) < CGRectGetHeight(innerRect) * 2.5)
    {
        return;
    }
    */

**Comment by yannickl** [comment]
Ok, I'll update/add this option and see what is the most convient for users.

**Comment by yannickl** [comment]
have you had time to test the changes?

**Comment by tbechtum** [comment]
Hi Yannick,
I did install your latest pod version weeks ago and it worked fine. Tomorrow I will check with pod update if I have the latest version installed. Please tell me if this is not meeting your test plans.

Thanks again for your work!
Thomas

Am 02.02.2015 um 18:49 schrieb Yannick Loriot <notifications@github.com<mailto:notifications@github.com>>:


have you had time to test the changes?

-

**Comment by tbechtum** [comment]
Hi Yannick,

I had already YLProgressBar (3.5.1) installed and this works fine.

Best regards,
Thomas

On 02 Feb 2015, at 20:35, Bechtum Thomas <Thomas.Bechtum@unibz.it<mailto:Thomas.Bechtum@unibz.it>> wrote:

Hi Yannick,
I did install your latest pod version weeks ago and it worked fine. Tomorrow I will check with pod update if I have the latest version installed. Please tell me if this is not meeting your test plans.

Thanks again for your work!
Thomas

Am 02.02.2015 um 18:49 schrieb Yannick Loriot <notifications@github.com<mailto:notifications@github.com>>:


have you had time to test the changes?
