### ISSUE TITLE
minimumFontSize is deprecated

### ISSUE THREAD

**Issue by tbechtum** [yannickl/YLProgressBar#21]
In Xcode Version 6.1.1 I get the following compiler warning
/Pods/YLProgressBar/YLProgressBar/YLProgressBar.m:323:25: 'minimumFontSize' is deprecated: first deprecated in iOS 6.0

**Comment by yannickl** [comment]
Thank you, I'll fix it this w-e. :)

**Comment by yannickl** [comment]
Problem fixed! Thank you for your help. :+1:
