### ISSUE TITLE
Text not updating sometimes

### ISSUE THREAD

**Issue by agibson73** [yannickl/YLProgressBar#23]
The bar fills correctly but sometimes the text gets stuck on a number. Specifically 10%.  If I restart the app it allows the text to update.  Clicking on items and removing them the progressbar and text go down normally. I am not using it in a download process more of an achievement tracking bar. Love YLProgressBar

**Comment by agibson73** [comment]
Specifically 10%

**Comment by yannickl** [comment]
Thank you for your report. I'll check that quickly. :+1:

**Comment by agibson73** [comment]
ok so it has something to do with indicatorTextLabel being set to nil. Sorry I am using this beyond the intended person but it looks beautiful for the purpose that I am trying to accomplish.

**Comment by agibson73** [comment]
Removing tell check for hasText has fixed my issue in the update progress.

**Comment by agibson73** [comment]
Removing thel check for hasText has fixed my issue in the update progress.

**Comment by yannickl** [comment]
Hi,

I found where the bug came from and I just fixed it. I'll update the podspec (for cocoapod) in the next weeks.

**Comment by agibson73** [comment]
Really a well done bar! I have customized it a bit but I think it is very well done.  Thanks for sharing it with the community.

**Comment by yannickl** [comment]
:+1: Thank you, I close the issue if you have any prob you can re-open it.
