### ISSUE TITLE
There is a white gap between border to progress bar

### ISSUE THREAD

**Issue by y0unghe** [yannickl/YLProgressBar#25]
I created the progress bar from storyboard, I change the UIView class to YLProgressBar. and then set the color in `viewDidLoad()`. 

```
progressBar.progressTintColor = UIColor.magentaColor()
progressBar.trackTintColor = UIColor.whiteColor()
progressBar.type = YLProgressBarType.Rounded
progressBar.stripesOrientation = YLProgressBarStripesOrientation.Vertical
![Uploading iOS Simulator Screen Shot Apr 12, 2015, 12.49.58.png . . .]()

progressBar.stripesDirection = YLProgressBarStripesDirection.Left
```

But there is a gap on the left, as you can see from pic below
![ios](https://cloud.githubusercontent.com/assets/1100727/7105455/090fbcde-e14d-11e4-952d-ab6288041020.png)

**Comment by yannickl** [comment]
Hi,

You can change the value of the `progressBarInset` property if you don't want this behaviour. By default there is a 1px inset.

Best

**Comment by mbLc** [comment]
Hi,

As you can see on izon90 screenshot, there is also a grey bar on the top, is it possible to remove it?
ProgressbarInset doesn't fix it.

Also, what is the property to remove the black shadow or change the shadow color on the stripes? They appear really black on the left.

Thanks for your help.
