### ISSUE TITLE
Indicator text doesn't show

### ISSUE THREAD

**Issue by iBCode** [yannickl/YLProgressBar#28]
Xcode 6.3.2, using YLProgressBar in storyboard, neither YLProgressBarIndicatorTextDisplayModeProgress nor YLProgressBarIndicatorTextDisplayModeTrack displays the default text.
Here is the code below for reference:
    // Initialize progress bar
    self.progressBar.progressTintColor = [UIColor greenColor];
    self.progressBar.indicatorTextDisplayMode = YLProgressBarIndicatorTextDisplayModeTrack;
    self.progressBar.behavior = YLProgressBarBehaviorIndeterminate;

**Comment by yannickl** [comment]
Where the problem occurs? On the storyboard or in the simulator/device?

I'll check it tomorrow.

**Comment by iBCode** [comment]
On the storyboard, simulator: iPhone 6, iPhone 4s (7.1) and iPhone 4s (8.3). And the demo didn't show percentage text occasionally when I toggled between YLProgressBarIndicatorTextDisplayModeTrack. How come?

**Comment by mattilla** [comment]
It occurred to me, too.
Xcode 6.3.2, using YLProgressBar in storyboard.
The '' YLProgressBarIndicatorTextDisplayModeProgress '' displays no text indicator while
the " YLProgressBarIndicatorTextDisplayModeTrack " displays as the attached image:
![img_3126](https://cloud.githubusercontent.com/assets/3965582/7951996/563bab32-09e1-11e5-8f2a-74742651c453.jpg)

**Comment by yannickl** [comment]
I tested it with Xcode 6.3.2 and I can't reproduce the issue. Can you create a minimal example project that produce the glitch?

**Comment by iBCode** [comment]
Here is the quick demo to reproduce this issue. 
https://github.com/iBCode/Demo
![ios simulator screen shot jun 4 2015 09 57 30](https://cloud.githubusercontent.com/assets/7181827/7975667/33398f24-0aa3-11e5-85b7-817e50c0ea1c.jpg)

**Comment by yannickl** [comment]
Is the last commit fixes the glitch?

**Comment by iBCode** [comment]
Not really, just a demo to show this issue. lol
