### ISSUE TITLE
cornerRadius not working

### ISSUE THREAD

**Issue by mrshih** [yannickl/YLProgressBar#32]
I can't disable cornerRadius by set to 0.

**Comment by yannickl** [comment]
You can set the `type` property with `YLProgressBarTypeFlat` value?

**Comment by mrshih** [comment]
Yes, After set YLProgressBarType value to YLProgressBarTypeFlat, cornerRadius disable now.

**Comment by mrshih** [comment]
But still confuse about cornerRadius property.

What is that property design for ?

**Comment by yannickl** [comment]
The `cornerRadius` property is designed to work with the `YLProgressBarTypeRounded` progresses. The property has been added after the initial conception and may need to be more consistent by setting automatically the type to `YLProgressBarTypeFlat` when the radius moves to 0.
