### ISSUE TITLE
Remove gradiant

### ISSUE THREAD

**Issue by chlebta** [yannickl/YLProgressBar#33]
Hello, 
How to remove gradient from flatProgress bar simple bar without black gradient at the begin

**Comment by yannickl** [comment]
Hi,

I don't understand your problem, please can you share an image (screenshot or whatever) to help me visualize it?

Best

**Comment by chlebta** [comment]
check this : 
![one](https://cloud.githubusercontent.com/assets/1204608/9468554/23c7a878-4b3a-11e5-82d9-3ae8dcaf7e75.png)
![two](https://cloud.githubusercontent.com/assets/1204608/9468555/271a9a26-4b3a-11e5-8849-7c32c020873f.png)

as you can see there's like black gradient there and her's my code  : 
```
 //progress bar
    _progressBar = [[YLProgressBar alloc] initWithFrame:CGRectMake(0.f, 10.f, self.view.frame.size.width, 50.f)];
    _progressBar.type = YLProgressBarTypeFlat;
    _progressBar.progressTintColor = secondaryColor;
    _progressBar.hideStripes = YES;
    [self.view addSubview:_progressBar];
```

**Comment by yannickl** [comment]
Ok, I understand,

The `progressTintColor` property automatically add the gradient. You should use the `progressTintColors` instead:

```objective-c
_progressBar.progressTintColors = @[secondaryColor];
```

**Comment by nightwolf-chen** [comment]
This is confusing. I think the ProgressTintColor property should include auto gradient function. It takes me sometime to find out how to disable the gradient,  thanks anyway!

**Comment by yannickl** [comment]
@nightwolf-chen With the latest version you can use the `uniformTintColor` property instead #45
