### ISSUE TITLE
Show indicatorTextLabel.text on top of progress instead of getting overlapped

### ISSUE THREAD

**Issue by peoplesoft** [yannickl/YLProgressBar#43]
Hi,
First of all, what a great library. Thank-you for the effort!

My question.
I was wondering if it would be possible to have the indicatorTextLabel text show above the progress instead of getting overlapped (see screenshot where the text "SOME TEXT" starts to hide behind the progress bar)

<img width="372" alt="screen shot 2016-06-30 at 4 52 55 pm" src="https://cloud.githubusercontent.com/assets/926916/16504112/4a93b070-3ee4-11e6-9bfc-2b3dcab07ad5.png">

```
NSArray *tintColors = @[[UIColor colorWithRed:33/255.0f green:180/255.0f blue:162/255.0f alpha:1.0f],
                            [UIColor colorWithRed:149/255.0f green:37/255.0f blue:36/255.0f alpha:1.0f];
  _progressBarRoundedSlim.progressTintColors        = tintColors;
  
    _progressBarRoundedSlim.hideStripes = YES;
    _progressBarRoundedSlim.trackTintColor = [UIColor whiteColor];
    _progressBarRoundedSlim.progressBarInset = 3;
    
    _progressBarRoundedSlim.indicatorTextLabel.text = @"SOME TEXT";
    _progressBarRoundedSlim.hideGloss = YES;
    
    _progressBarRoundedSlim.indicatorTextDisplayMode = YLProgressBarIndicatorTextDisplayModeTrack;
    _progressBarRoundedSlim.indicatorTextLabel.font  = [UIFont fontWithName:@"Arial-BoldMT" size:20];
    _progressBarRoundedSlim.indicatorTextLabel.textColor = [UIColor blackColor];
```

Thank-you.

**Comment by yannickl** [comment]
Hi,

Sorry for the late, I just published a new pod version with the possibility to do that with the `YLProgressBarIndicatorTextDisplayModeFixedRight` enum case. :)

```objective-c
_progressBarRoundedSlim.indicatorTextDisplayMode = YLProgressBarIndicatorTextDisplayModeFixedRight;
```

I hope it'll be ok for you!

**Comment by peoplesoft** [comment]
Brilliant! Thank-you :)
