### ISSUE TITLE
Vertical gradient

### ISSUE THREAD

**Issue by Natelegreat1** [yannickl/YLProgressBar#46]
Not sure if #15 meant a vertical progress bar, but I would like to have the colours show in a vertical gradient like I have done in the Pause button.
Is this possible currently? I can't seem to find any way...
Thanks!

![screen shot 2016-08-25 at 1 56 10 pm](https://cloud.githubusercontent.com/assets/2666640/17980084/baadae70-6acb-11e6-9712-ad655be0087f.png)

**Comment by yannickl** [comment]
Hi,

No the issue #15 is not for this purpose. Have you tried to use the pattern color?

```objective-c
UIImage *image                    = [UIImage imageNamed:@"gradient.png"];
progress.progressTintColor = [UIColor colorWithPatternImage:image];
```

**Comment by Natelegreat1** [comment]
@yannickl This is an interesting idea that would work! I am changing the gradient pattern dynamically though so I would need a whole lot of image. Thanks for getting back to me though!
