### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by odedharth** [yannickl/YLProgressBar#47]
Not compatible with Swift 3 and xcode 8

**Comment by yannickl** [comment]
Thank you for warn I'll update the project ASAP. 👍

**Comment by yannickl** [comment]
I just tested and it works fine for me. What is your issue and your coding environment?

**Comment by odedharth** [comment]
Sorry seems fine, thanks!

**Comment by mkaya93** [comment]
@yannickl I have a problem with progrestintColors. there is the code and output logs.

```
progressView = YLProgressBar(frame: CGRect(x: 0,y: 0,width: self.view.frame.size.width,height: 13))
        progressView.type = .flat
        progressView.hideStripes = true
        progressView.hideTrack = true
        progressView.progressStretch = false
        progressView.backgroundColor = UIColor.clear
        let firstColor = UIColor(hexString: "FEA616")
        let secondColor = UIColor(hexString: "FB773D")
        progressView.progress = 0
        progressView.progressTintColors = [firstColor,secondColor]
```

` Bons[2375:484064] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_SwiftValue CGColor]: unrecognized selector sent to instance 0x17145bdb0'`
