### ISSUE TITLE
Still slight gloss when turned off

### ISSUE THREAD

**Issue by luluminshall** [yannickl/YLProgressBar#51]
There still seems to be a slight bit of white gloss when it's turned off, I would expect it to be completely flat. Would be great if you could address this

**Comment by yannickl** [comment]
Can you share a screenshot please?

However if you want a flat progress you can set the `type` to `YLProgressBarTypeFlat`.

**Comment by ipodishima** [comment]
@luluminshall is it related to #62 ?
