### ISSUE TITLE
Right to left support

### ISSUE THREAD

**Issue by khusro017** [yannickl/YLProgressBar#60]
Hi,
Is there any support for right to left applications. I am able to rotate the progress bar but with that the progress indicator also got mirrored.
I tried to rotate the progress bar with : 

progressBar.transform = CGAffineTransform(rotationAngle: CGFloat(M_PI))
self.progressBar.indicatorTextLabel.transform = CGAffineTransform(rotationAngle: CGFloat(-M_PI)) 

then the text label indicator also got mirrored and i am not able to undo that i.e only to rotate the progress bar, not the label.
![screen shot 2017-11-21 at 5 33 23 pm](https://user-images.githubusercontent.com/23547491/33075199-1eaf5c7c-cee2-11e7-997f-f5bc85aa107f.png)

        
       
Thank you.

**Comment by Khaled-elsedek** [comment]
did you fix it ?
